name = "uuid_now"
version = "1.0.1"
license = "MIT"
author = "jordan4ibanez"
maintainer = "jordan4ibanez"
copyright = "Copyright 2024, jordan4ibanez"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[dependencies]
forthread = { git = "https://github.com/jordan4ibanez/forthread" }

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
